### ISSUE TITLE
Send cloud-event to Keptn: The wait for event does not wait long enough

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#1]
Looks like it the add is just trying once to get eval complete event.  Needs to wait longer.

It would be nice to have this configurable with a default.

![image](https://user-images.githubusercontent.com/24907089/85057334-a15d8100-b16e-11ea-947b-7e0fbd79b08c.png)

**Comment by heydenb** [comment]
The waiting flag here is now removed
