### ISSUE TITLE
Add version number to the friendlyName

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#10]
Azure Devops does not show you what version you have when editing the pipeline.  One must go to org settings to do this.

![image](https://user-images.githubusercontent.com/24907089/85885577-8fa15c80-b7b2-11ea-9098-afc81a721665.png)

I suggest adding this to the friendlyName value in each of the task.json files and the vss-extension.json files

here is an example
https://github.com/dt-demos/azure-devops-extension-dt-push-event/blob/develop/pushEvent/src/v1/task.json#L4

here is example for how looks like for project & tasks
![image](https://user-images.githubusercontent.com/24907089/85885707-c7a89f80-b7b2-11ea-82c0-fa6eec6c86e1.png)

![image](https://user-images.githubusercontent.com/24907089/85885723-d2633480-b7b2-11ea-82af-7d295c706fee.png)

**Comment by robertjahn** [comment]
I know this may not be common practice to put this in the friendly name, but I do find it hard to know what version is installed without going to the org. settings.  Open to your ideas.

**Comment by robertjahn** [comment]
Maybe do this just for the DEV version of the extension once that is in place.

**Comment by robertjahn** [comment]
@heydenb  -- Now that we have a DEV version....it is impossible to tell which is which
![image](https://user-images.githubusercontent.com/24907089/86598764-99258400-bf6b-11ea-9676-9b730cb346e0.png)

**Comment by robertjahn** [comment]
same goes with the service connection, can't tell what is what.
![image](https://user-images.githubusercontent.com/24907089/86600174-b3606180-bf6d-11ea-867f-eb403f941e7c.png)

**Comment by robertjahn** [comment]
@heydenb  -- I still would like some differentiation when I have the DEV and PROD extensions installed.  Here is a mockup of what I mean by adding `DEV` the name and `DEV version #` to the extention.  By having this, once can tell what the pipeline is using.

![image](https://user-images.githubusercontent.com/24907089/89422121-e6c81480-d702-11ea-81ab-2e92f9d98206.png)

**Comment by heydenb** [comment]
The DEV Version now has DEV and version available
