### ISSUE TITLE
Add release notes files to the project

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#12]
summarize the changes in a given version.  Include the github issue # as reference in the file too.

See this project as an example
https://github.com/keptn-contrib/dynatrace-service/tree/master/releasenotes

Look at this for a way to automate the process

https://pypi.org/project/semversioner/

**Comment by christian-kreuzberger-dtx** [comment]
Done - https://github.com/keptn-sandbox/keptn-azure-devops-extension/blob/master/CHANGELOG.md
