### ISSUE TITLE
Document the process to contribute

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#15]
Add details for how to build and deploy the application in case someone wants to fork this.  Point out how need to adjust the subscription ID

**Comment by christian-kreuzberger-dtx** [comment]
Initial Documentation can be found here: https://github.com/keptn-sandbox/keptn-azure-devops-extension/blob/master/README_DEV.md

**Comment by christian-kreuzberger-dtx** [comment]
we believe the changes in README_DEV.md should be sufficient. We have cleaned up several dependencies, so the dev workflow is much easier now.
