### ISSUE TITLE
Create a TEST version of the extension

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#16]
We should have two versions of the extension, a public one (PRODUCTION) one and a non-public (TEST) one.   This will allow for integration testing before a change is promoted.

For the TEST version, in the marketplace you can specify the organizations who can install it.
![image](https://user-images.githubusercontent.com/24907089/86389388-3af35b00-bc64-11ea-9be5-a2e2cdbc3a1b.png)

Take a look at this script for reference to create an automation scripts for promoting code 
https://bitbucket.org/keptn/keptn-quality-gate/src/master/ci-scripts/release.sh

**Comment by heydenb** [comment]
Created a system based on gulp that allows us to make the distiction between Dev and the public version
