### ISSUE TITLE
Use variable as the default value for project, stage, service for the task forms

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#19]
The user can set these in the variable group.

**Comment by robertjahn** [comment]
@heydenb -- Looks like this is working....but question...  In the send event, this is what is in the help...is this still TRUE?  Now that we use these variables, should you remove that logic and help message?

![image](https://user-images.githubusercontent.com/24907089/86627260-01895b00-bf96-11ea-98b7-ed93698e0275.png)

**Comment by robertjahn** [comment]
block by https://github.com/keptn-sandbox/keptn-azure-devops-extension/issues/2.  Please move back to "TESTING" once ready for me to test again.

**Comment by heydenb** [comment]
Hey Rob. I would keep the logic and comments. So it can be used any way you like. When using the variables, they have priority.
