### ISSUE TITLE
Project Setup: Monitoring field

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#25]
What is the purpose of this field?  Looking at code it does nothing.  If this is not a requirement, then please remove the option.

![image](https://user-images.githubusercontent.com/24907089/86598492-32a06600-bf6b-11ea-8c44-50e731c95b79.png)

**Comment by heydenb** [comment]
It does something. Sending the "configure monitoring dynatrace" to keptn.
