### ISSUE TITLE
Send Event: Add default for start and end time

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#26]
As to help with standardization, use default variables for start and end time.  Propose:
$(startTime)
$(endTime)

NOW
![image](https://user-images.githubusercontent.com/24907089/86599071-1e109d80-bf6c-11ea-9a91-48879ed5f4ac.png)

PROPOSED

![image](https://user-images.githubusercontent.com/24907089/86599104-2cf75000-bf6c-11ea-8ae9-9e9ff1a3c271.png)

**Comment by heydenb** [comment]
Now also support timeframe and defaulting to 30m since Keptn 0.7.3
