### ISSUE TITLE
Wait for Keptn Event:  What is the lookup logic?

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#3]
Not sure what the app is looking for now, but I would expect to have to configure keptn project, service, stage so that this knows what to look for.  Or is this suppose to looking for a particular keptn-context-id and event type?

![image](https://user-images.githubusercontent.com/24907089/85057695-14ff8e00-b16f-11ea-9881-496350145f1d.png)

**Comment by heydenb** [comment]
You don't need to configure anything more. It uses the context which was added as a pipeline variable by the Send keptn event task.

**Comment by robertjahn** [comment]
What is the use case for a separate "Wait for Keptn Event" task?   if you have that wait for event checkbox in the "send event", not 100% sure we need this.

If you want a separate task, then maybe add in the configuration input for the "Wait for Keptn Event" , the keptn context variable that you are using as the default.  I could see a scenario where you want to pass in keptn-context or scenario where you might have two keptn events you might me waiting for,

**Comment by robertjahn** [comment]
after discussion, we will expose the variable for keptnContext.  See https://github.com/keptn-sandbox/keptn-azure-devops-extension/issues/18
