### ISSUE TITLE
Duplicate "Mark build as ... on result warning from Keptn" field in wait for event

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#31]
Here is screen shot of doubled up field

![image](https://user-images.githubusercontent.com/24907089/89421165-ae740680-d701-11ea-9371-40f6496f000a.png)

**Comment by heydenb** [comment]
This is not an issue. One field is about "what to do on keptn error" and the other is about "what to do on keptn warning"
