### ISSUE TITLE
Support keptn 0.7.0 add resource endpoint

### ISSUE THREAD

**Issue by kristofre** [keptn-sandbox/keptn-azure-devops-extension#32]
In Keptn 0.7.0 the endpoint to add resources has changed to the `configuration-service`.
To update the extension, I suggest the following change to https://github.com/keptn-sandbox/keptn-azure-devops-extension/blob/017c3b6f621f0b65d182f67e679aec2123031d4c/PrepareKeptnEnvTask/index.ts#L215

old, keptn 0.6.x
`url: input.keptnApiEndpoint + '/v1/project/' + input.project + '/stage/' + input.stage + '/service/' + input.service + '/resource',`

new, keptn 0.7.0
`url: input.keptnApiEndpoint + '/configuration-service/v1/project/' + input.project + '/stage/' + input.stage + '/service/' + input.service + '/resource',`

**Comment by heydenb** [comment]
Hey Kristof.
Issue is fixed. Version 0.1.17 is just released to the marketplace and takes into account the keptn version automatically via the metadata api call. This one is not available in 0.6.x but I catch the 404.
