### ISSUE TITLE
Wrong handling of timeframe leads to invalid quality gate runs

### ISSUE THREAD

**Issue by grabnerandi** [keptn-sandbox/keptn-azure-devops-extension#33]
The Azure DevOps Extension has recently been extended to leverage the timeframe option of a new REST Endpoint that was introduced with 0.7.3. The REST API Endpoint looks like this
```
POST /project/{projectName}/stage/{stageName}/service/{serviceName}/evaluation
{
  "labels": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  },
  "start": "",
  "end": "",
  "timeframe": "30m"
}
```

Seems like in the current implementation you are defaulting to timeframe=30m when no start or end time is specified. 

However - the current implementation doesnt work because it is not making the call to the new **evaluation** api endpoint but still use the generic /event endpoint sending a `sh.keptn.event.start-evaluation` event with an additional field timeframe. 
This leads to a problem because the generic `sh.keptn.event.start-evaluation` doesn't allow a timeframe field. The timeframe is only available in the /evaluation endpoint which will then take this value, calculate start/end and then sends the `sh.keptn.event.start-evaluation` with the correct start/end fields

What therefore needs to happen is a change in the current implementation to call the new `evaluation` api endpoint instead of using the `event` endpoint. that should solve it

**Comment by heydenb** [comment]
Implemented, but during testing ran into another issue about timeformat.
see: https://github.com/keptn/keptn/issues/2972

**Comment by diegorqc** [comment]
Stumble upon this problem today, right now it's using the default timeframe of 5 mins which is not enough for our use case. Do you have any updates regarding this?

**Comment by heydenb** [comment]
Default which is passed is now 30m
