### ISSUE TITLE
Update Azure extension to include waiting for 0.8.4 keptn workflow events.

### ISSUE THREAD

**Issue by mariarolbiecka** [keptn-sandbox/keptn-azure-devops-extension#35]
At the moment the only event that you can wait for using Keptn extension is deprecated "evaluation-done" event.

![image](https://user-images.githubusercontent.com/27851457/132059969-a0af55f9-1793-49d3-a907-3d8ba35c7bf7.png)

It would be great to have "Wait for Keptn Event" task updated.

**Comment by heydenb** [comment]
You are right. This is something I want to update ASAP.
Could you help me out with the API call? You probably know exactly which endpoint and how the json body should look like. If you could attach an example I will make some time for the fix.

**Comment by heydenb** [comment]
Just released 1.3.6 of the extension. Its supporting any type of waiting for sequence now. If it's an evaluation the feature to mark the pipeline as red or orange still applies. If it's another type of event, you will recieve the JSON string as a pipeline variable so you can do whatever you want with it. See updated README file.
