### ISSUE TITLE
Send cloud-event to Keptn: Add feature to control evaluation of results

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/keptn-azure-devops-extension#7]
Add configuration option to control how the quality gate results are processed.  

Here is reference to one way to do this.

- pass_on_warning - a fail keptn result status will stop the pipeline
- fail_on_warning- a fail or warning keptn result status will stop the pipeline
- ignore - will not process the keptn status

Here is reference code that implements this logic
https://bitbucket.org/keptn/keptn-quality-gate/src/239ea4a5679a93c06908cf5f9a065aa36a1aa20d/pipe/pipe.sh#lines-91

**Comment by heydenb** [comment]
The WaitFor task now contains two extra fields to control this behavior.
"markBuildOnError" and "markBuildOnWarning" with possible values:
- "NOTHING": "as passed - do nothing",
- "WARNING": "as passed with warnings",
- "FAILED": "as failed"

**Comment by robertjahn** [comment]
The drop down list is doubled up in the Web UI

![image](https://user-images.githubusercontent.com/24907089/88457938-274ca600-ce58-11ea-84af-4d8499b0309a.png)
